### PR TITLE
To identify correct end of the regex

### PR DESCRIPTION
**Pull request by CGLOB**
When a regular expression is detected this saveRegex crawls for the correct end of it and will saves the whole regex.

### CODE REVIEW

**Comment by tedivm** [comment]
Thanks for the PR! This weekend I'll get tests working again so we can confirm no regressions.

**Comment by tedivm** [comment]
I'm rather confused as to why tests aren't running- can you try closing and reopening the pull request?

**Comment by CGLOB** [comment]
sure

**Comment by tedivm** [comment]
Okay lets try something else- can you make a new branch in your repository and open the pull request from that branch? I think the issue is that it's not linking the tests in your repository (where they're technically running now) to the pull request in part because they're running in your default branch for the repo.

**Comment by CGLOB** [comment]
ok on it

**Comment by tedivm** [comment]
Once that is done I would also like it is you could add a test case for this bug to the test suite to make sure that this actually resolves it and so that future changes don't cause a regression.

To do that put a file named "regex_end_string.js" to-

`./JShrink/tree/master/tests/Resources/jshrink/input/`

And then add a second file with the expected output to-

`./JShrink/tree/master/tests/Resources/jshrink/output/`

Ideally this example should be one that failed before your PR, and that is also resolved by that PR. If you have any trouble please let me know!

**Comment by CGLOB** [comment]
> Once that is done I would also like it is you could add a test case for this bug to the test suite to make sure that this actually resolves it and so that future changes don't cause a regression.
> 
> To do that put a file named "regex_end_string.js" to-
> 
> `./JShrink/tree/master/tests/Resources/jshrink/input/`
> 
> And then add a second file with the expected output to-
> 
> `./JShrink/tree/master/tests/Resources/jshrink/output/`
> 
> Ideally this example should be one that failed before your PR, and that is also resolved by that PR. If you have any trouble please let me know!

Sure i will add that and will let you know if any issue. Thanks.

**Comment by CGLOB** [comment]
> Okay lets try something else- can you make a new branch in your repository and open the pull request from that branch? I think the issue is that it's not linking the tests in your repository (where they're technically running now) to the pull request in part because they're running in your default branch for the repo.

First i will open new PR then i will work on the test.

**Comment by CGLOB** [comment]
Please check this PR https://github.com/tedious/JShrink/pull/116

**Comment by tedivm** [comment]
Okay I got tests running here!

**Comment by CGLOB** [comment]
with your latest changes the issue no longer reproducible. So my solution no longer needed. Hence i am closing this PR. Thanks for your attention and help.

**Comment by tedivm** [comment]
It would be great if you could share an example of what broke, either here or in a pull request, so that we can protect against regressions.

**Pull request closed without merging**
