### PR TITLE
Fix regular expressions breaking after arithmetic operations

### LINKED ISSUE #83: Incorrectly detected JS comments in regular expressions
## Background

I just bumped into an issue with JShrink when minifying/combining JS code that is using [core-js](https://github.com/zloirock/core-js).

The issue comes e.g. form these lines in the core-js version 2 code:
https://github.com/zloirock/core-js/blob/6a3fe85136aaae0e3b099c96a05a5ceb1f515a50/modules/es7.string.pad-end.js#L8-L10

There are popular JS modules using core-js (particularly version 2), such as [\@babel/polyfill](https://github.com/babel/babel/blob/f92c2ae830dbb32013a36fa74facd2ef95b9947d/packages/babel-polyfill/package.json).

## Explanation of the issue

To simplify the line in the core-js code, these types of JavaScript source strings will produce the same error:

- `var test = a * /regtest\//.test(userAgent);`
- `var test = a + /regtest\//.test(userAgent);`
- `var test = a - /regtest\//.test(userAgent);`

The last part after the two slashes is stripped out and the output for each of the strings is respectively as follows:

- `var test = a * /regtest\`
- `var test = a + /regtest\`
- `var test = a - /regtest\`

This will obviously break any JS code that comes after that.

To further outline the issue here, each of the test strings above work correctly if you take out the calculation in front of the regular expression (i.e. `a *`, `a +`, `a -` or `a /` in the examples above).

## Steps to reproduce

Create a sample project using the packagist version (the same issue is also at the GitHub repo's latest code):

```bash
$ mkdir jshrinktest && cd jshrinktest && composer require tedivm/jshrink
```

Then, create a test script to run the examples:

```php
<?php
require "vendor/autoload.php";

function test($js) {
  echo JShrink\Minifier::minify($js);
  echo PHP_EOL;
}

echo "This does NOT work:" . PHP_EOL;
test('var test = a * /regtest\//.test(userAgent);');
test('var test = a + /regtest\//.test(userAgent);');
test('var test = a - /regtest\//.test(userAgent);');

echo "This works OK:" . PHP_EOL;
test('var test = /regtest\//.test(userAgent);');
```

### PR DESCRIPTION
**Pull request by ahukkanen**
Fix #83

### CODE REVIEW

**Comment by tedivm** [comment]
You're awesome, thanks for the contribution!

**Comment by ahukkanen** [comment]
Any chance you could release a new version with this fix included?

**Comment by tedivm** [comment]
Released as 1.3.2

**Comment by ahukkanen** [comment]
Cheers!

**Pull request merged**
