### PR TITLE
performance tweaks

### PR DESCRIPTION
**Pull request by birdspider**
The incentive was that with the xdebug profiler on I ran into timeout (30s) issues, 
tried to improve it a bit. You might be interested in this, i have tested a bit, all seems fine.

* strict equality tests
* regex /S optimize flag
* omit cast to bool in while
* empty instead of counting

with xdebug on, this got me 50% faster generation (10 instead of 20s)
without xdebug its barely noticible

### CODE REVIEW

**Comment by birdspider** [comment]
sry, forgot to add:
* changed `echo X . Y;` to `echo X , Y;`

**Comment by mikeytown2** [comment]
What's the improvement? Also, how much of a benefit does using echo comma instead of echo period make? Echo using a comma seems like a bad idea for readability.

**Comment by tedivm** [comment]
I made a quick script which did 1,000,000 operations for each method and here were the results-

With commas- 0.3482
With periods- 0.3496

The comma stuff is a micro optimization that will have no real performance benefit. Everything else looks pretty good though.

**Comment by birdspider** [comment]
regarding `,` vs. `.` in echo: 

it's about concating a string before `echo`ing the whole which normaly is a waste; since here we are in output buffer context anyway, it does not matter as much. I just changed it out of habit. 
Should I undo those `echo` changes ?

**Comment by tedivm** [comment]
If you wouldn't mind undoing them I would appreciate it. I'm going to give the code one more review tonight when I'm out of work and then I'll merge it.

Thanks for the PR!

**Comment by birdspider** [comment]
@mikeytown2 , the actual improvement in production mode is limited, but when using the xdebug profiler (which I was using to profile other stuff) runtime went down approx. from 20s to 10s (per js package ~ 0.5MB minfied), and since I was packaging 2+ packages I kept hitting the 30s mark. Instead of blindly extending the timeout value I went out to try and speed things up.

**Comment by tedivm** [comment]
Thanks for the PR. If you have any other ideas on increasing performance please send them my way.

**Pull request merged**
