### PR TITLE
github CI workflow for automated testing

### PR DESCRIPTION
**Pull request by syteknet-core**

### CODE REVIEW

**Comment by tedivm** [comment]
Travis no longer gives open source projects credit, so we need to migrate to github actions or circleci.

**Comment by syteknet-core** [comment]
@tedivm, the PR is changed and includes a github workflow for automated testing now. to get everything running flawlessly some packages needed to be updated. Hopefully we can get a release for php8 ready soon!

**Comment by janbarasek** [comment]
In PR #98, the deployment of automatic tests is solved (unit test + PhpStan). At the same time, I fix a number of bugs and the tests pass.

**Comment by syteknet-core** [comment]
@janbarasek you could have just merged this branch in your PR! it also updates phpunit and the test cases to the recent version.

**Comment by janbarasek** [comment]
@syteknet-core I don't want to merge your branch to mine. This increases control complexity and reduces the chance of final merging. Each feature must be added individually.

**Comment by syteknet-core** [comment]
@janbarasek - i fully agree so it is very puzzeling why you have added that feature (github-CI) to the scope of your PR then anyways after this PR was created, you came here to comment on that. so basically you are increasing control complexity here! we have two conflicting PRs and your github ci implementation is incomplete since it is missing PHP-8 tests...

if you solve this by merging in this PR, removing github CI from your PR - or adding PHP-8 tests manually is up to you!

**Comment by syteknet-core** [comment]
IMHO remving github CI from your PR would be the correct thing todo. since, as you already mentioned, one PR one feature i think we agree on that.

**Comment by tedivm** [comment]
This PR is no longer needed as a separate PR has moved the project to Github actions and has updated PHPUnit.

**Pull request closed without merging**
